\section{Referência da Classe br::ufscar::lince::ginga::core::mmi::DuplicateException}
\label{classbr_1_1ufscar_1_1lince_1_1ginga_1_1core_1_1mmi_1_1DuplicateException}\index{br::ufscar::lince::ginga::core::mmi::DuplicateException@{br::ufscar::lince::ginga::core::mmi::DuplicateException}}


{\ttfamily \#include $<$DuplicateException.h$>$}

\subsection*{Métodos Públicos}
\begin{DoxyCompactItemize}
\item 
{\bf DuplicateException} (string mensagem)
\item 
virtual {\bf $\sim$DuplicateException} ()  throw ()
\item 
virtual const char $\ast$ {\bf what} () const   throw ()
\end{DoxyCompactItemize}


\subsection{Descrição Detalhada}
Esta exceção deve ser lançada quando um método tenta adicionar um entidade duplicada a um conjunto. A mensagem passada para a exceção deve especificar quais os parâmetros que foram passados para o método. 

\subsection{Construtores \& Destrutores}
\index{br::ufscar::lince::ginga::core::mmi::DuplicateException@{br::ufscar::lince::ginga::core::mmi::DuplicateException}!DuplicateException@{DuplicateException}}
\index{DuplicateException@{DuplicateException}!br::ufscar::lince::ginga::core::mmi::DuplicateException@{br::ufscar::lince::ginga::core::mmi::DuplicateException}}
\subsubsection[{DuplicateException}]{\setlength{\rightskip}{0pt plus 5cm}br::ufscar::lince::ginga::core::mmi::DuplicateException::DuplicateException (string {\em mensagem})}\label{classbr_1_1ufscar_1_1lince_1_1ginga_1_1core_1_1mmi_1_1DuplicateException_a41116c5e92ee7bc8bd7930702560eff9}
Construtor com um parametro. 
\begin{DoxyParams}{Parâmetros}
\item[{\em mensagem}]que aparece. \end{DoxyParams}


Referenciado por what().

\index{br::ufscar::lince::ginga::core::mmi::DuplicateException@{br::ufscar::lince::ginga::core::mmi::DuplicateException}!$\sim$DuplicateException@{$\sim$DuplicateException}}
\index{$\sim$DuplicateException@{$\sim$DuplicateException}!br::ufscar::lince::ginga::core::mmi::DuplicateException@{br::ufscar::lince::ginga::core::mmi::DuplicateException}}
\subsubsection[{$\sim$DuplicateException}]{\setlength{\rightskip}{0pt plus 5cm}br::ufscar::lince::ginga::core::mmi::DuplicateException::$\sim$DuplicateException ()  throw ()\hspace{0.3cm}{\ttfamily  [virtual]}}\label{classbr_1_1ufscar_1_1lince_1_1ginga_1_1core_1_1mmi_1_1DuplicateException_a6b7fca1382694b9b2e074691e2cc7e50}
Destrutor da classe. 

\subsection{Métodos}
\index{br::ufscar::lince::ginga::core::mmi::DuplicateException@{br::ufscar::lince::ginga::core::mmi::DuplicateException}!what@{what}}
\index{what@{what}!br::ufscar::lince::ginga::core::mmi::DuplicateException@{br::ufscar::lince::ginga::core::mmi::DuplicateException}}
\subsubsection[{what}]{\setlength{\rightskip}{0pt plus 5cm}const char $\ast$ br::ufscar::lince::ginga::core::mmi::DuplicateException::what () const  throw ()\hspace{0.3cm}{\ttfamily  [virtual]}}\label{classbr_1_1ufscar_1_1lince_1_1ginga_1_1core_1_1mmi_1_1DuplicateException_aaab3d2b4e158fea6bb28d70485d93eee}
Método chamado automaticamente quando uma exeção não-\/captura é lançada. \begin{DoxyReturn}{Retorna}
ponteiro para char com o valor da mensagem 
\end{DoxyReturn}


Referências DuplicateException().



A documentação para esta classe foi gerada a partir dos seguintes arquivos:\begin{DoxyCompactItemize}
\item 
include/DuplicateException.h\item 
src/DuplicateException.cpp\end{DoxyCompactItemize}
